[package]
name = "usdr"
version = "0.0.0"
edition = "2021"

description = "Rust implementation of USD (placeholder)"
license = "Apache-2.0 OR MIT"
readme = "README.md"
repository = "https://github.com/CAD97/usdr"

[dependencies]
